### ISSUE TITLE
example 3.1.2 works but warns about illegal reflection. 

### ISSUE THREAD

**Issue by RMHogervorst** [bechbd/graph-databases-in-action#10]
I downloaded the samples from the github page, downloaded both gremlin server and gremlin console on my macbook . Running macos big sur 11.1. 

When I run 
`❯ bin/gremlin.sh -i $BASE_DIR/chapter03/scripts/3.1-simple-social-network.groovy`

I get this warning 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/MYNAME/Downloads/apache-tinkerpop-gremlin-console-3.4.9/lib/groovy-2.5.11-indy.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by RMHogervorst** [comment]
I have absolutely no idea if this is bad, expected, or not a problem, but I'll let you know anyways.

**Comment by alexott** [comment]
all examples were tested with Java 8, it looks like that you're using Java 11 - I'm not sure that it's natively supported already

**Comment by joshperryman** [comment]
@RMHogervorst thank you for inquiring about this. The messages are not a problem for the use of Apache TinkerPop's Gremlin Console. They are known to occur for certain configurations, such as when using Java versions past Java 8. 

For more information see: [TINKERPOP-2292](https://issues.apache.org/jira/browse/TINKERPOP-2292) and [GROOVY-8339](https://issues.apache.org/jira/browse/GROOVY-8339).
